- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
      msg: "name is {{Name}} and seat is {{Preference}} time is {{Time}}"