- name: looping 
  hosts: web
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }    
    - { name: 'git', state: 'present' }
    - { name: 'postgress', state: 'present' }
